import {Builder, By, Capabilities, WebDriver, until} from 'selenium-webdriver'
import { poleStar } from './configurePS2'

const ps = new poleStar() 


test('select a motor', async () => {
    await ps.navigate('https://www.polestar.com/us/')
    await ps.click(ps.cookies)
    await ps.click(ps.menu)
    await ps.click(ps.ps2)
    await ps.click(ps.configure)
    await ps.click(ps.longRange)
    await ps.driver.wait(until.elementLocated(ps.rangeConfirmation))
    await ps.driver.sleep(2000)
})

test('select an exterior color', async() => {
    await ps.navigate('https://www.polestar.com/us/')
   // await ps.click(ps.cookies)
    await ps.click(ps.menu)
    await ps.click(ps.ps2)
    await ps.click(ps.configure)
    await ps.click(ps.exterior)
    await ps.click(ps.snow)
    await ps.driver.sleep(500)
    await ps.driver.wait(until.elementLocated(ps.snowConfirm))
    await ps.click(ps.thunder)
    await ps.driver.sleep(500)
    await ps.driver.wait(until.elementLocated(ps.thunderConfirm))
    await ps.click(ps.jupiter)
    await ps.driver.sleep(500)
    await ps.driver.wait(until.elementLocated(ps.jupiterConfirm))
    await ps.click(ps.midnight)
    await ps.driver.sleep(500)
    await ps.driver.wait(until.elementLocated(ps.midnightConfirm))
    await ps.click(ps.space)
    await ps.driver.sleep(500)
    await ps.driver.wait(until.elementLocated(ps.spaceConfirm))
    await ps.driver.sleep(2000) 
}) 

test('select an interior', async() => {
    await ps.navigate('https://www.polestar.com/us/')
   // await ps.click(ps.cookies)
    await ps.click(ps.menu)
    await ps.click(ps.ps2)
    await ps.click(ps.configure)
    await ps.click(ps.interior)
    await ps.click(ps.charcoal3D)
    await ps.driver.wait(until.elementLocated(ps.charcaolConfirm))
    await ps.click(ps.zinc)
    await ps.driver.wait(until.elementLocated(ps.zincConfirm))
    await ps.click(ps.slate)
    await ps.click(ps.acceptAndContinue)
    await ps.driver.wait(until.elementLocated(ps.slateConfirm))
    await ps.click(ps.charcoalWeave)
    await ps.driver.wait(until.elementLocated(ps.charcoalWeaveConfirm))
    await ps.click(ps.nappa)
    await ps.driver.wait(until.elementLocated(ps.nappaConfirm))
    await ps.driver.sleep(2000)
}) 

test('select a package', async() => {
    await ps.navigate('https://www.polestar.com/us/')
  //  await ps.click(ps.cookies)
    await ps.click(ps.menu)
    await ps.click(ps.ps2)
    await ps.click(ps.configure)
    await ps.click(ps.packs)
    await ps.click(ps.pilot)
    await ps.driver.sleep(1000)
    await ps.click(ps.add)
    await ps.driver.wait(until.elementLocated(ps.pilotConfirm))
    await ps.click(ps.plus)
    await ps.driver.sleep(1000)
    await ps.click(ps.add)
    await ps.driver.sleep(1000)
    await ps.click(ps.acceptAndContinue)
    await ps.driver.wait(until.elementLocated(ps.plusConfirm))
    await ps.click(ps.performance)
    await ps.driver.sleep(1000)
    await ps.click(ps.add)
    await ps.driver.sleep(1000)
    await ps.click(ps.acceptAndContinue)
    await ps.driver.wait(until.elementLocated(ps.performanceConfirm))
    await ps.driver.sleep(2000)
}) 

test('select wheels', async() => {
    await ps.navigate('https://www.polestar.com/us/')
  //  await ps.click(ps.cookies)
    await ps.click(ps.menu)
    await ps.click(ps.ps2)
    await ps.click(ps.configure)
    await ps.click(ps.wheels)
    await ps.click(ps.blackDiamond)
    expect(await ps.driver.findElement(ps.wheelsConfirmation).getText()).toContain("19'' 5-Double Spoke Black Diamond Cut Alloy Wheel")
    await ps.driver.sleep(1000)
    await ps.click(ps.blackSilver)
    await ps.driver.sleep(2000)
    expect(await ps.driver.findElement(ps.wheelsConfirmation).getText()).toContain("20'' 5-V Spoke Black Silver Alloy Wheel (+ $1,300)")
    await ps.click(ps.blackPolished)
    await ps.driver.sleep(2000)
    await ps.click(ps.acceptAndContinue)
    await ps.driver.sleep(2000)
    expect(await ps.driver.findElement(ps.polishedConfirm).getText()).toContain('20" 4-Y Spoke Black Polished Forged Alloy Wheel - Summer Tire')
    await ps.driver.sleep(2000)
}) 

test('selecting add-ons', async() => {
    await ps.navigate('https://www.polestar.com/us/')
  //  await ps.click(ps.cookies)
    await ps.click(ps.menu)
    await ps.click(ps.ps2)
    await ps.click(ps.configure)
    await ps.click(ps.mats)
    await ps.click(ps.addMat1)
    await ps.driver.sleep(500)
    await ps.click(ps.addMat2)
    await ps.driver.sleep(500)
    await ps.click(ps.exitMats)
    await ps.driver.wait(until.elementLocated(ps.mat1Confirm))
    await ps.driver.wait(until.elementLocated(ps.mat2Confirm))
    await ps.click(ps.loadCarrier)
    await ps.click(ps.add)
    await ps.driver.wait(until.elementLocated(ps.loadConfirm))
    await ps.click(ps.towbarHitch)
    await ps.click(ps.add)
    await ps.driver.wait(until.elementLocated(ps.towbarConfirm))
    await ps.driver.sleep(2000)
    
    await ps.driver.quit()
}) 